#!/bin/bash

set -e
export LANG=

# CouchDBInstall
echo '*** BEGIN Install CouchDB'

# Installed as part of ccnq-base.

# Install default config file
sudo /etc/init.d/couchdb stop
# Double-enforce (currently having issues with this).
sudo killall couchdb beam.smp heart || echo OK

# Apparently using /etc/couchdb/local.d/ccnq3 does not work.
COUCHDB_CONFIG=/etc/couchdb/local.ini

sudo tee "${COUCHDB_CONFIG}" <<EOT >/dev/null
[httpd]
port = 5984
bind_address = ::
WWW-Authenticate = Basic realm="couchdb"

[couch_httpd_auth]
require_valid_user = true

[log]
level = error

[admins]
admin = ${ADMIN_PASSWORD}
EOT
sudo chown couchdb.couchdb "${COUCHDB_CONFIG}"

sudo /etc/init.d/couchdb start

# The following commands could be used instead, but due to various issues
# (e.g. pre-existing admin password) we're better off rewriting local.ini.
# curl -X PUT "http://127.0.0.1:5984/_config/httpd/port" -d '5984'
# curl -X PUT "http://127.0.0.1:5984/_config/log/level" -d '"error"'
# curl -X PUT "http://127.0.0.1:5984/_config/httpd/bind_address" -d '"::"'
# curl -X PUT "http://127.0.0.1:5984/_config/httpd/WWW-Authenticate" -d 'Basic realm="couchdb"'
# curl -X PUT "http://127.0.0.1:5984/_config/admins/admin" -d "\"${ADMIN_PASSWORD}\""
# curl -X PUT "http://127.0.0.1:5984/_config/couch_httpd_auth/require_valid_user" -d "\"true\""

echo '*** END Install CouchDB Completed OK.'
