#!/bin/bash

set -e
export LANG=

# CouchDBInstall
echo '*** BEGIN Install CouchDB'

# CouchDB 1.1.0 is only in unstable as of 2011-08-23.
sudo aptitude install -y couchdb

# Install default config file
ADMIN_PASSWORD=`openssl rand 256 -hex`

sudo tee /etc/couchdb/local.d/ccnq3 <<EOT >/dev/null
[httpd]
port = 5984
bind_address = ::
WWW-Authenticate = Basic realm="couchdb"

[couch_httpd_auth]
require_valid_user = true

[log]
level = error

[admins]
admin = ${ADMIN_PASSWORD}
EOT

sudo /etc/init.d/couchdb stop
sudo /etc/init.d/couchdb start

echo '*** END Install CouchDB Completed OK.'
