#!/bin/bash

set -e
export LANG=

# CouchDBInstall
echo '*** BEGIN Install CouchDB'

# CouchDB 1.1.0 is only in unstable as of 2011-08-23.
sudo aptitude install -y couchdb/unstable

# Install default config file

# Using 128 or higher does not work.
ADMIN_PASSWORD=`openssl rand 64 -hex`

# Apparently using /etc/couchdb/local.d/ccnq3 does not work.
COUCHDB_CONFIG=/etc/couchdb/local.ini

sudo tee "${COUCHDB_CONFIG}" <<EOT >/dev/null
[httpd]
port = 5984
bind_address = ::
WWW-Authenticate = Basic realm="couchdb"

[couch_httpd_auth]
require_valid_user = true

[log]
level = error

[admins]
admin = ${ADMIN_PASSWORD}
EOT
sudo chown couchdb.couchdb "${COUCHDB_CONFIG}"

sudo /etc/init.d/couchdb stop
sudo /etc/init.d/couchdb start

echo '*** END Install CouchDB Completed OK.'
