#!/bin/bash

set -e
export LANG=

# NodeInstall
echo '** BEGIN Install Node and npm'

sudo aptitude install -y daemon
sudo aptitude install -y -t unstable nodejs nodejs-dev

mkdir -p ~/Node
cd ~/Node
if npm -v | egrep -q '^1\.0'; then
  echo "** WARNING: Using existing npm version `npm -v`"
else
(
  sudo rm -rf npm/
  git clone http://github.com/isaacs/npm.git
  cd npm
  git submodule update --init --recursive
  sudo make install
)
fi

sudo npm -g install coffee-script

echo '** END Install Node and npm Completed OK.'
