#!/bin/bash

set -e
export LANG=

echo '** BEGIN Install Node, npm, and coffeescript'

# We offer nodejs 0.6.5 under ccnq-base.

# Node.js 0.6.5 contains npm.

sudo npm -g install coffee-script

echo '** END Install Node, npm and coffeescript Completed OK.'
