#!/bin/bash

set -e
export LANG=

# FIXME In CouchDB 1.1.0, we can instantiate an SSL server from within
#       CouchDB, so stunnel is no longer required.
#       However this script should be integrated with the CouchDB script
#       so that /etc/couchdb/local.ini reflects the proper configuration.

echo '*** BEGIN Creating SSL key for CouchDB'

# Generate SSL key and CSR
cd /etc/couchdb
umask 0077
sudo rm -f server.key.pass server.key server.csr server.crt stunnel.pem
sudo openssl genrsa -des3 -out server.key.pass 4096 <<'EOT'
password
password
EOT
sudo openssl rsa -in server.key.pass -out server.key <<'EOT'
password
EOT
sudo openssl req -new -key server.key -out server.csr <<'EOT'
FR
Finistere
Plouzane
shimaore.net
shimaore.net
shimaore.net
admin@shimaore.net


EOT
sudo openssl x509 -req -in server.csr -out server.crt -signkey server.key -days 3660
sudo cat server.crt server.key | sudo tee stunnel.pem >/dev/null
sudo rm /etc/stunnel/server.*

echo '*** Create SSL key for CouchDB Completed OK.'
