#!/usr/bin/env bash

set -e
export LANG=
SRC="`pwd`"
DIR=/etc/ccnq3
CONF=${DIR}/host.json

./bootstrap/prepare
./bootstrap/node

HOSTNAME=`hostname`

sudo mkdir -p "${DIR}"
if [ -e "${CONF}" ]; then
  echo "** WARNING: This host has already been bootstrapped. The previous configuration will be used. To start over please remove ${CONF} before using this script."
else
  if [ "x$1" == "x" ]; then
    echo "** You must provide a reference URI."
    exit
  else
    URI=$1
    shift
  fi

  # make_id
  sudo tee "${CONF}" <<JSON >/dev/null
  {
    "_id": "host:${HOSTNAME}",
    "type": "host",
    "host": "${HOSTNAME}",
    "provisioning": {
      "couchdb_uri": "$URI"
    }
  }
JSON
fi

# Cleanup any previous run
(cd && rm -rf node_modules)

(cd && npm install "${SRC}/"applications/host)

(cd && npm run-script ccnq3_host stop) || echo
(cd && npm run-script ccnq3_host start)

(cd && npm install "${SRC}/"applications/commands)

# On an non-bootstrap host, the "commands" module is started later
# since we first need to donwload the configuration to know the
# location of the database.
