#!/usr/bin/env bash
# (c) 2011 Stephane Alnet
# License: APGL3+

set -e
export LANG=
SRC="`pwd`"
DIR=/etc/ccnq3
CONF=${DIR}/host.json

if [ -e "${CONF}" ]; then
  echo "** ERROR: $CONF already exists **"
  exit 1
fi

./bootstrap/prepare
./bootstrap/node

HOSTNAME=`hostname`

echo "Create ${DIR}"
sudo mkdir -p "${DIR}"
sudo chown `whoami` "${DIR}"

if [ "x$1" == "x" ]; then
  echo "** ERROR: You must provide a reference URI **"
  exit
else
  CDB_URI="$1"
  shift
fi

echo "Creating ${CONF}"
sudo tee "${CONF}" <<JSON >/dev/null
{
  "_id": "host:${HOSTNAME}",
  "type": "host",
  "host": "${HOSTNAME}",
  "provisioning": {
    "couchdb_uri": "${CDB_URI}"
  }
, "applications": [
    "applications/host"
  ]
, "source": "${SRC}"
}
JSON
# Add any server-specific applications at the end of the (space-delimited) string.
sudo chown `whoami` "${CONF}"

(cd && cd "${SRC}" \
    && npm install )

echo "Cleanup"
${SRC}/cleanup
echo "Update"
${SRC}/update.coffee

echo "Restart"
${SRC}/restart.coffee

echo "Installation done."
