#!/usr/bin/env bash
# (c) 2011 Stephane Alnet
# License: APGL3+

set -e
export LANG=
SRC="`pwd`"
DIR=/etc/ccnq3
CONF=${DIR}/host.json

./bootstrap/prepare
./bootstrap/node

HOSTNAME=`hostname`

sudo mkdir -p "${DIR}"
if [ -e "${CONF}" ]; then
  echo "** WARNING: $CONF already exists, re-using it"
else
  if [ "x$1" == "x" ]; then
    echo "** Proceeding with installation of CouchDB on local host ${HOSTNAME}."
    . bootstrap/couchdb
    CDB_URI="http://admin:${ADMIN_PASSWORD}@${HOSTNAME}:5984"
  else
    CDB_URI="$1"
    shift
  fi

  echo "Bootstrapping database using ${CDB_URI}"
  sudo tee "${CONF}" <<JSON >/dev/null
  {
    "_id": "host:${HOSTNAME}",
    "type": "host",
    "host": "${HOSTNAME}",
    "bootstrap": {
      "couchdb_uri": "${CDB_URI}"
    },
    "users": {
      "couchdb_uri": "${CDB_URI}/_users"
    },
    "provisioning": {
      "couchdb_uri": "${CDB_URI}/provisioning"
    },
    "commands": {
      "couchdb_uri": "${CDB_URI}/commands"
    },
    "logger": {
      "couchdb_uri": "${CDB_URI}/logger"
    }
  }
JSON
fi

# Cleanup any previous run
(cd && rm -rf node_modules)

(cd && npm install "${SRC}/"applications/_users)
(cd && npm run-script ccnq3_users security)
(cd && npm uninstall  ccnq3_users)

(cd && npm install "${SRC}/"applications/provisioning)
(cd && npm run-script ccnq3_provisioning couchapps)
(cd && npm uninstall  ccnq3_provisioning)

(cd && npm install "${SRC}/"applications/host)
(cd && npm run-script ccnq3_host couchapps)
(cd && npm run-script ccnq3_host bootstrap)

# Starting host service
(cd && npm run-script ccnq3_host stop || echo)
(cd && npm run-script ccnq3_host start)


# TODO [Local] Could be done from ccnq3_host
(cd && npm install "${SRC}/"applications/commands)
(cd && npm run-script ccnq3_commands couchapps)

(cd && npm run-script ccnq3_commands stop || echo)
(cd && npm run-script ccnq3_commands start)

# TODO [Global] Could be done from ccnq3_host
(cd && npm install "${SRC}/"applications/roles)
(cd && npm run-script ccnq3_roles couchapps)

(cd && npm install "${SRC}/"applications/portal)
(cd && npm run-script ccnq3_portal couchapps)

# TODO [Global] Code these as "ccnq3_host" templates.
(cd && npm run-script ccnq3_roles stop || echo)
(cd && npm run-script ccnq3_roles start)

(cd && npm run-script ccnq3_portal stop || echo)
(cd && npm run-script ccnq3_portal start)


# Other services are started using the "host" framework.

echo
echo "To manage your system, please access ${CDB_URI}/provisioning/_design/app/index.html or a suitable redirection."
