#!/usr/bin/env bash
# (c) 2011 Stephane Alnet
# License: APGL3+

set -e
export LANG=
SRC="`pwd`"
DIR=/etc/ccnq3
CONF=${DIR}/host.json

./bootstrap/prepare
./bootstrap/node

HOSTNAME=`hostname`

sudo mkdir -p "${DIR}"
sudo chown `whoami` "${DIR}"
if [ -e "${CONF}" ]; then
  echo "** WARNING: $CONF already exists"
else
  if [ "x$1" == "x" ]; then
    echo "** Proceeding with installation of CouchDB on local host ${HOSTNAME}."

    # Using 128 or higher does not work.
    ADMIN_PASSWORD=`openssl rand 64 -hex`

    export ADMIN_PASSWORD
    . bootstrap/couchdb
    CDB_URI="http://admin:${ADMIN_PASSWORD}@${HOSTNAME}:5984"
  else
    # Provide a URI on the command-line for example if you already
    # have a CouchDB/BigCouch cluster and want to have CCNQ use it.
    CDB_URI="$1"
    shift
  fi

  echo "Bootstrapping database using ${CDB_URI}"
  # make_id
  sudo tee "${CONF}" <<JSON >/dev/null
  {
    "_id": "host:${HOSTNAME}",
    "type": "host",
    "host": "${HOSTNAME}",
    "admin": {
      "couchdb_uri": "${CDB_URI}"
    }
  }
JSON
  sudo chown `whoami` "${CONF}"

  sudo tee "${DIR}/applications" <<TEXT >/dev/null
# creates the usercode database: must be first since all others depend on it
applications/usercode
# creates the provisioning database: must be second
applications/provisioning
applications/host
# roles then portal
applications/roles
applications/portal
applications/inbox
public
# Add any server-specific applications here.
TEXT
  sudo chown `whoami` "${DIR}/applications"
fi

${SRC}/cleanup
${SRC}/update-system
${SRC}/restart

echo "==== Install the local host ===="
(cd && npm run-script ccnq3_host bootstrap)

echo "==== Done ===="
echo
echo "To manage your system, please access ${CDB_URI}/provisioning/_design/host/index.html or a suitable redirection."
