#!/usr/bin/env bash
# (c) 2011 Stephane Alnet
# License: APGL3+

set -e
export LANG=
SRC="`pwd`"
DIR=/etc/ccnq3
CONF=${DIR}/host.json

# Changes in the update file are idempotent (for the same release).
IS_SYSTEM=`./read-json /etc/ccnq3/host.json admin.system`

for application in  `./read-json ${CONF} applications`; do
  echo "==== Update ${application} ===="
  (cd && cd "${SRC}/${application}" \
      && npm install \
      && if [ "x${IS_SYSTEM}" == 'xtrue' ]; then
           npm run-script couchapps;
         fi)
done
