#!/usr/bin/env bash
# (c) 2011 Stephane Alnet
# License: APGL3+

set -e
export LANG=
SRC="`pwd`"
DIR=/etc/ccnq3
CONF=${DIR}/host.json

# Changes in the update file are idempotent (for the same release).

for application in  `egrep -v '^#' ${DIR}/applications`; do
  echo "==== Update ${application} ===="
  (cd && cd "${SRC}/${application}" \
      && npm install \
      && npm run-script couchapps)
done
