#!/bin/bash

# FIXME This would need to be ran on the host(s) that will run the node code
# (agents or web UIs)

set -e
export LANG=

echo '*** Install ccnq3'

echo '*** Install pre-requisites'
(
  mkdir -p ~/Node
  export http_proxy="${NEED_PROXY}"
  npm config set proxy "$http_proxy"
  npm install nodemailer node-uuid

  # This version might work better.
  # ( cd ~/Node && rm -rf connect          && git clone git://stephane.shimaore.net/git/connect.git           && cd connect          && npm install )
  npm install connect
  # This one is required.
  ( cd ~/Node && rm -rf zappa            && git clone git://stephane.shimaore.net/git/zappa.git             && cd zappa            && npm install )

)

echo '*** Completed OK.'

