#!/bin/bash

if [[ $# -eq 1 ]] && [[ $1 == 'autoconf' ]]; then
        echo "yes"
        exit
fi

if [[ $# -eq 1 ]] && [[ $1 == 'config' ]]; then
  cat <<EOT ;
graph_title Calls
graph_args -l 0
graph_vlabel active calls
graph_category voice
sofia_calls_ACTIVE.label SIP active
sofia_calls_ACTIVE.max 50000
sofia_calls_ACTIVE.min 0
sofia_calls_ACTIVE.draw AREA
sofia_calls_DOWN.label SIP down
sofia_calls_DOWN.max 50000
sofia_calls_DOWN.min 0
sofia_calls_DOWN.draw STACK
sofia_calls_EARLY.label SIP early
sofia_calls_EARLY.max 50000
sofia_calls_EARLY.min 0
sofia_calls_EARLY.draw STACK
sofia_calls_HELD.label SIP held
sofia_calls_HELD.max 50000
sofia_calls_HELD.min 0
sofia_calls_HELD.draw STACK
sofia_calls_RINGING.label SIP ringing
sofia_calls_RINGING.max 50000
sofia_calls_RINGING.min 0
sofia_calls_RINGING.draw AREA
sofia_calls.label SIP calls
sofia_calls.max 25000
sofia_calls.min 0
sofia_calls.draw LINE2
EOT
  exit
fi

fs_cli -p CCNQ -x 'show calls' | awk '
BEGIN { active = down = early = held = ringing = total = 0 }
/,ACTIVE,/ { active++ }
/,DOWN,/   { down++ }
/,EARLY,/  { early++ }
/,HELD,/   { held++ }
/,RINGING,/ { ringing++ }
/ total./  { total = $1 }
END {
  print "sofia_calls_ACTIVE.value " active
  print "sofia_calls_DOWN.value " down
  print "sofia_calls_EARLY.value " early
  print "sofia_calls_HELD.value " held
  print "sofia_calls_RINGING.value " ringing
  print "sofia_calls.value " total
}
'
