#!/bin/bash
# (c) 2011 Stephane Alnet
# License: AGPL3+

if [[ $# -eq 1 ]] && [[ $1 == 'autoconf' ]]; then
        echo "yes"
        exit
fi

if [[ $# -eq 1 ]] && [[ $1 == 'config' ]]; then
  cat <<EOT ;
graph_title Dialogs
graph_args -l 0
graph_vlabel dialogs
graph_category voice
opensips_dialogs.label Dialogs
opensips_dialogs.max 25000
opensips_dialogs.min 0
opensips_dialogs.draw LINE2
EOT
  exit
fi

echo -n "opensips_dialogs.value "
/usr/sbin/opensipsctl fifo dlg_list | egrep '^dialog::' | wc -l
