#!/bin/bash
# (c) 2011 Stephane Alnet

if [[ $# -eq 1 ]] && [[ $1 == 'autoconf' ]]; then
        echo "yes"
        exit
fi

if [[ $# -eq 1 ]] && [[ $1 == 'config' ]]; then
  cat <<EOT ;
graph_title Registered Users
graph_args -l 0
graph_vlabel AORs
graph_category voice
opensips_registered.label Users
opensips_registered.max 25000
opensips_registered.min 0
opensips_registered.draw LINE2
EOT
  exit
fi

echo -n "opensips_registered.value "
/usr/sbin/opensipsctl fifo ul_dump brief | egrep '^\s*AOR::' | wc -l
