#!/usr/bin/env bash

NAME=replication
SCRIPT=ccnq3_${NAME}.coffee
CONFIG=/etc/ccnq3/$NAME.config

case "$1" in
  start)
    daemon -n "${NAME}" -r -o daemon.debug -- "${SCRIPT}" "${CONFIG}"
    ;;

  stop)
    daemon -n "${NAME}" -o daemon.debug --stop
    ;;

  restart)
    daemon -n "${NAME}" -o daemon.debug --restart
    ;;

  status)
    if daemon -n "${NAME}" --running; then echo "Running"; else echo "Not Running"; fi
    ;;

  *)
    echo "Usage: $0 (start|stop|restart|status)"
    exit 2
    ;;

esac

exit 0
