#!/usr/bin/env bash

NAME=registration
SCRIPT=registration.coffee

SCRIPT_DIR=`dirname "$0"`
if [ "x${SCRIPT_DIR}" == "x." ]; then
  SCRIPT_DIR=`pwd`
fi

case "$1" in
  start)
    daemon -n "${NAME}" -r -D "${SCRIPT_DIR}" -o daemon.debug -- coffee "${SCRIPT}"
    ;;

  stop)
    daemon -n "${NAME}" -o daemon.debug --stop
    ;;

  restart)
    daemon -n "${NAME}" -o daemon.debug --restart
    ;;

  status)
    if daemon -n "${NAME}" --running; then echo "Running"; else echo "Not Running"; fi
    ;;

  *)
    echo "Usage: $0 (start|stop|restart|status)"
    exit 2
    ;;

esac

exit 0
